version: "3"

services:
  traefik:
    image: traefik:v2.0.1
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.httpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.httpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.httpchallenge.acme.email=vitkarpenko@gmail.com.com"
      - "--certificatesresolvers.httpchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./data/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy
  dokuwiki:
    image: linuxserver/dokuwiki:arm32v7-latest
    container_name: dokuwiki
    environment:
      - TZ=Europe/Moscow
    expose:
      - "80"
      - "443"
    volumes:
      - ./data/dokuwiki:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dokuwiki.rule=Host(`wiki.vitkarpenko.xyz`)"
      - "traefik.port=443"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dokuwiki.entrypoints=websecure"
      - "traefik.http.routers.dokuwiki.tls.certresolver=httpchallenge"
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy
