version: "3"

services:
  traefik:
    image: traefik:v2.0.1
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.httpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.httpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.httpchallenge.acme.email=vitkarpenko@gmail.com"
      - "--certificatesresolvers.httpchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./data/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy
  dokuwiki:
    image: linuxserver/dokuwiki:arm32v7-latest
    container_name: dokuwiki
    environment:
      - TZ=Europe/Moscow
    expose:
      - "80"
      - "443"
    volumes:
      - ./data/dokuwiki:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # HTTP -> HTTPS
      - "traefik.http.routers.dokuwiki-http.rule=Host(`notes.vitkarpenko.xyz`)"
      - "traefik.http.middlewares.dokuwiki-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dokuwiki-http.middlewares=dokuwiki-https-redirect@docker"
      - "traefik.http.routers.dokuwiki-http.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.dokuwiki-https.rule=Host(`notes.vitkarpenko.xyz`)"
      - "traefik.http.routers.dokuwiki-https.entrypoints=websecure"
      - "traefik.http.routers.dokuwiki-https.tls.certresolver=httpchallenge"
      - "traefik.port=443"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
  calibre:
    image: linuxserver/calibre-web:arm32v7-latest
    container_name: calibre
    environment:
      - TZ=Europe/Moscow
    expose:
      - "8083"
    volumes:
      - ./data/calibre/data:/config
      - ./data/calibre/library:/books
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # HTTP -> HTTPS
      - "traefik.http.routers.calibre-http.rule=Host(`books.vitkarpenko.xyz`)"
      - "traefik.http.middlewares.calibre-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.calibre-http.middlewares=calibre-https-redirect@docker"
      - "traefik.http.routers.calibre-http.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.calibre-https.rule=Host(`books.vitkarpenko.xyz`)"
      - "traefik.http.routers.calibre-https.entrypoints=websecure"
      - "traefik.http.routers.calibre-https.tls.certresolver=httpchallenge"
      - "traefik.port=8083"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
  rss:
    image: linuxserver/freshrss:arm32v7-latest
    container_name: rss
    environment:
      - TZ=Europe/Moscow
    expose:
      - "80"
      - "443"
    volumes:
      - ./data/rss/data:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # HTTP -> HTTPS
      - "traefik.http.routers.rss-http.rule=Host(`rss.vitkarpenko.xyz`)"
      - "traefik.http.middlewares.rss-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.rss-http.middlewares=rss-https-redirect@docker"
      - "traefik.http.routers.rss-http.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.rss-https.rule=Host(`rss.vitkarpenko.xyz`)"
      - "traefik.http.routers.rss-https.entrypoints=websecure"
      - "traefik.http.routers.rss-https.tls.certresolver=httpchallenge"
      - "traefik.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy
