version: "3"

services:
        #########
        # Torrent
        #########
        deluge:
                image: lscr.io/linuxserver/deluge
                container_name: deluge
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=Europe/London
                        - DELUGE_LOGLEVEL=error #optional
                volumes:
                        - ./data/deluge/data:/config
                        - /data/nfs:/downloads
                ports:
                        - 8112:8112
                        - 6881:6881
                        - 6881:6881/udp
                restart: unless-stopped
