version: "3"

services:
  #########
  # Torrent
  #########
  deluge:
    image: linuxserver/deluge:arm32v7-latest
    container_name: deluge
    environment:
      - TZ=Europe/Moscow
    expose:
      - "8112"
    volumes:
      - ./data/deluge/data:/config
      - ../media/torrent:/downloads
    restart: unless-stopped
