version: "3"

services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - DB_HOST=bookstack_maria
      - DB_USER=bookstack
      - DB_PASS=bookstack
      - DB_DATABASE=bookstack
    volumes:
      - ./data/bookstack:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_maria
  bookstack_maria:
    image: linuxserver/mariadb
    container_name: bookstack_maria
    environment:
      - TZ=Europe/Moscow
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack
    volumes:
      - ./data/bookstack_maria:/config
    restart: unless-stopped
